---
- name: Ensure /opt/devops directory and file exist
  hosts: all
  become: yes
  tasks:
    - name: Create /opt/devops directory
      file:
        path: /opt/devops
        state: directory

    - name: Create info.txt file with content
      copy:
        dest: /opt/devops/info.txt
        content: "Hello from Ansible!\n"
...

